[project]
name = "calculator-agent"
version = "0.0.1"
description = "calculator-agent"
authors = [{ name = "John Doe", email = "john.doe@myemail.com" }]
dependencies = [
    "uipath>=2.2.0, <2.3.0",
]
requires-python = ">=3.11"
