[project]
name = "csv-processor"
version = "0.0.1"
description = "csv-processor"
dependencies = [
  "uipath>=2.8.0, <2.9.0",
  "pandas>=2.3.3",
]
requires-python = ">=3.11"

[dependency-groups]
dev = [
    "uipath-dev>=0.0.15",
]
