[project]
name = "list-mcp-agent"
version = "0.0.1"
description = "UiPath MCP agent"
authors = [{ name = "John Doe", email = "john.doe@myemail.com" }]
dependencies = [
    "uipath>=2.1.169, <2.2.0",
    "mcp>=1.0.0",
    "httpx>=0.27.0"
]
requires-python = ">=3.11"
