[project]
name = "tree-recursive-function"
version = "0.0.1"
description = "tree-recursive-function"
authors = [{ name = "John Doe", email = "john.doe@myemail.com" }]
dependencies = [
    "uipath>=2.8.0, <2.9.0",
]
requires-python = ">=3.11"

[dependency-groups]
dev = [
    "uipath-dev>=0.0.47",
]
