[project]
name = "documents-testcase"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "John Doe" }]
requires-python = ">=3.10"
dependencies = [
    "uipath",
]

[tool.uv.sources]
uipath = { path = "../../", editable = true }
